include $(RISCV_ROOTFS_HOME)/Makefile.app

# Compilation flags

CROSS_COMPILE ?= riscv64-unknown-linux-gnu-

AS      = $(CROSS_COMPILE)gcc
CC      = $(CROSS_COMPILE)gcc
CXX     = $(CROSS_COMPILE)g++
LD      = $(CROSS_COMPILE)gcc
OBJDUMP = $(CROSS_COMPILE)objdump

INCLUDES  = $(addprefix -I, $(INC_DIR))

# Build type: Release by default, Debug enables symbols.
BUILD_TYPE ?= Release

ifeq ($(BUILD_TYPE),Debug)
CFLAGS_OPT   := -O0 -g
CXXFLAGS_OPT := -O0 -g
else
CFLAGS_OPT   := -O2
CXXFLAGS_OPT := -O2
endif

CFLAGS   += $(CFLAGS_OPT) -MMD $(INCLUDES)
CXXFLAGS += $(CXXFLAGS_OPT) -MMD $(INCLUDES)

# Files to be compiled
OBJS = $(addprefix $(DST_DIR)/, $(addsuffix .o, $(basename $(SRCS))))

# Compilation patterns
$(DST_DIR)/%.o: %.cpp
	@echo + CXX $<
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -c -o $@ $<
$(DST_DIR)/%.o: %.c
	@echo + CC $<
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c -o $@ $<
$(DST_DIR)/%.o: %.S
	@echo + CC $<
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c -o $@ $<

$(APP): $(OBJS)
	@echo + LD $@
	@$(LD) -o $(APP) $(OBJS) $(LDFLAGS)
	@$(OBJDUMP) -d $@ > $(patsubst %,%.txt,$@)

# Dependencies
DEPS = $(addprefix $(DST_DIR)/, $(addsuffix .d, $(basename $(SRCS))))
-include $(DEPS)