include $(RISCV_ROOTFS_HOME)/Makefile.app

# Compilation flags

CLANG_TARGET      ?= --target=riscv64-unknown-linux-gnu
CLANG_SYSROOT     ?= --sysroot=$(RISCV)/sysroot
CLANG_GCC_TOOLCHAIN ?= --gcc-toolchain=$(RISCV)
CLANG_FLAGS       ?= $(CLANG_TARGET) $(CLANG_SYSROOT) $(CLANG_GCC_TOOLCHAIN)

AS      = clang $(CLANG_FLAGS)
CC      = clang $(CLANG_FLAGS)
CXX     = clang++ $(CLANG_FLAGS)
LD      = clang $(CLANG_FLAGS) -no-pie
OBJDUMP = llvm-objdump

INCLUDES  = $(addprefix -I, $(INC_DIR))

CFLAGS   += -O0 -fno-PIC -MMD $(INCLUDES)
CXXFLAGS += -O0 -fno-PIC -MMD $(INCLUDES)

# Files to be compiled
OBJS = $(addprefix $(DST_DIR)/, $(addsuffix .o, $(basename $(SRCS))))

# Compilation patterns
$(DST_DIR)/%.o: %.cpp
	@echo + CXX $<
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -c -o $@ $<
$(DST_DIR)/%.o: %.c
	@echo + CC $<
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c -o $@ $<
$(DST_DIR)/%.o: %.S
	@echo + CC $<
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c -o $@ $<

$(APP): $(OBJS)
	@echo + LD $@
	@$(LD) -o $(APP) $(OBJS) $(LDFLAGS)
	@$(OBJDUMP) -d $@ > $(patsubst %,%.txt,$@)

# Dependencies
DEPS = $(addprefix $(DST_DIR)/, $(addsuffix .d, $(basename $(SRCS))))
-include $(DEPS)