/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _DASICS_DUMMY_ABI_H
#define _DASICS_DUMMY_ABI_H

#define DUMMY_MAINCALL_FIRST	0x44550000UL

enum dummy_maincall_service {
	DUMMY_MC_DOWN_WRITE = DUMMY_MAINCALL_FIRST,
	DUMMY_MC_RTNL_LOCK,
	DUMMY_MC_LINK_REGISTER,
	DUMMY_MC_COND_RESCHED,
	DUMMY_MC_LINK_UNREGISTER,
	DUMMY_MC_RTNL_UNLOCK,
	DUMMY_MC_UP_WRITE,
	DUMMY_MC_ALLOC_NETDEV,
	DUMMY_MC_REGISTER_NETDEVICE,
	DUMMY_MC_FREE_NETDEV,
	DUMMY_MC_ETHER_SETUP,
	DUMMY_MC_GET_RANDOM_BYTES,
	DUMMY_MC_ALLOC_PCPU_STATS,
	DUMMY_MC_FREE_PERCPU,
	DUMMY_MC_DEV_LSTATS_ADD,
	DUMMY_MC_SKB_TIMESTAMP,
	DUMMY_MC_KFREE_SKB,
	DUMMY_MC_DEV_LSTATS_READ,
	DUMMY_MC_CARRIER_ON,
	DUMMY_MC_CARRIER_OFF,
	DUMMY_MC_STRLCPY_DRIVER,
	DUMMY_MC_GET_NETDEV_OPS,
	DUMMY_MC_GET_ETHTOOL_OPS,
	DUMMY_MC_GET_LINK_OPS,
	DUMMY_MC_RTNL_LINK_UNREGISTER,
	DUMMY_MC_LAST = DUMMY_MC_RTNL_LINK_UNREGISTER,
};

struct dummy_maincall_result {
	long status;
	unsigned long value;
};

#endif /* _DASICS_DUMMY_ABI_H */
