#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
  printf 'Usage: %s OUTPUT\n' "$0" >&2
  exit 1
fi

output=$1
rm -f -- "$output"

cat <<EOF >>"$output"
# This file is auto-generated
# Do not edit this file directly

dir /bin 755 0 0
dir /etc 755 0 0
dir /dev 755 0 0
dir /lib 755 0 0
dir /lib/riscv64-linux-gnu 755 0 0
dir /proc 755 0 0
dir /sbin 755 0 0
dir /sys 755 0 0
dir /tmp 755 0 0
dir /usr 755 0 0
dir /mnt 755 0 0
dir /usr/bin 755 0 0
dir /usr/lib 755 0 0
dir /usr/sbin 755 0 0
dir /var 755 0 0
dir /var/tmp 755 0 0
dir /root 755 0 0
dir /var/log 755 0 0
dir /usr/share 755 0 0
dir /usr/share/udhcpc 755 0 0

nod /dev/console 644 0 0 c 5 1
nod /dev/null 644 0 0 c 1 3
EOF

LIBS=()
LIBS+=(ld-linux-riscv64-lp64d.so.1)

for lib in "${LIBS[@]}"; do
    p="$RISCV/lib/$lib"
    if [[ ! -f "$p" ]]; then
        printf 'Could not find library %s\n' "$p" >&2
        exit 1
    fi
    printf 'file /lib/%s %s 755 0 0\n' "$lib" "$p" >>"$output"
done

LIBS=()
LIBS+=(libc.so.6)
LIBS+=(libdl.so.2)
LIBS+=(libm.so.6)
LIBS+=(libpthread.so.0)
LIBS+=(libresolv.so.2)

for lib in "${LIBS[@]}"; do
    p="$RISCV/lib/$lib"
    if [[ ! -f "$p" ]]; then
        printf 'Could not find library %s\n' "$p" >&2
        exit 1
    fi
    printf 'file /lib/riscv64-linux-gnu/%s %s 755 0 0\n' \
      "$lib" "$p" >>"$output"
done

cat <<EOF >>"$output"
file /bin/busybox ${INITRAMFS_ROOT}/bin/busybox 755 0 0
file /etc/inittab ${INITRAMFS_ROOT}/../files/etc/inittab 755 0 0
file /etc/shadow ${INITRAMFS_ROOT}/../files/etc/shadow 600 0 0
file /etc/passwd ${INITRAMFS_ROOT}/../files/etc/passwd 600 0 0
file /usr/share/udhcpc/default.script ${INITRAMFS_ROOT}/../files/usr/share/udhcpc/default.script 755 0 0
slink /init /bin/busybox 755 0 0

file /lib/riscv64-linux-gnu/libtirpc.so.3 ${INITRAMFS_ROOT}/lib/libtirpc.so.3 755 0 0
EOF

BINS=()
BINS+=(bw_file_rd)
BINS+=(bw_mem)
BINS+=(bw_mmap_rd)
BINS+=(bw_pipe)
BINS+=(bw_tcp)
BINS+=(bw_unix)
BINS+=(disk)
BINS+=(enough)
BINS+=(flushdisk)
BINS+=(hello)
BINS+=(lat_connect)
BINS+=(lat_ctx)
BINS+=(lat_fcntl)
BINS+=(lat_fifo)
BINS+=(lat_fs)
BINS+=(lat_http)
BINS+=(lat_mem_rd)
BINS+=(lat_mmap)
BINS+=(lat_ops)
BINS+=(lat_pagefault)
BINS+=(lat_pipe)
BINS+=(lat_proc)
BINS+=(lat_rpc)
BINS+=(lat_select)
BINS+=(lat_sem)
BINS+=(lat_sig)
BINS+=(lat_syscall)
BINS+=(lat_tcp)
BINS+=(lat_udp)
BINS+=(lat_unix)
BINS+=(lat_unix_connect)
BINS+=(line)
BINS+=(lmdd)
BINS+=(lmhttp)
BINS+=(loop_o)
BINS+=(memsize)
BINS+=(mhz)
BINS+=(msleep)
BINS+=(par_mem)
BINS+=(par_ops)
BINS+=(stream)
BINS+=(timing_o)
BINS+=(tlb)
BINS+=(perf)

for bin in "${BINS[@]}"; do
    printf 'file /bin/%s %s/bin/%s 755 0 0\n' \
      "$bin" "$INITRAMFS_ROOT" "$bin" >>"$output"
done

########################################################################

# Recursively add files and subdirectories under ${INITRAMFS_ROOT}/my-dir to ramfs

target_directory="${INITRAMFS_ROOT}/my-dir"
mkdir -p -- "$target_directory"
log=$output

process_directory() {
  local dir="$1"
  local item
  local path
  local file_mode

  for item in "$dir"/*; do
    [[ -e "$item" || -L "$item" ]] || continue
    if [[ -d "$item" ]]; then
      path=${item#"$INITRAMFS_ROOT"}
      printf 'dir %s 755 0 0\n' "$path" >>"$log"
      process_directory "$item"
    elif [[ -f "$item" ]]; then
      path=${item#"$INITRAMFS_ROOT"}
      file_mode=$(stat -c '%a' -- "$item")
      [[ "$file_mode" =~ ^[0-7]{3,4}$ ]] || {
        printf 'Invalid regular-file mode for %s: %s\n' "$item" "$file_mode" >&2
        return 1
      }
      printf 'file %s %s %s 0 0\n' "$path" "$item" "$file_mode" >>"$log"
    fi
  done
}

if [[ ! -d "$target_directory" ]]; then
  printf 'Target directory does not exist: %s\n' "$target_directory" >&2
  exit 1
fi

# Process user-defined directories.
abs_path=$(realpath -- "$target_directory")
ramfs_path=${abs_path#"$INITRAMFS_ROOT"}
printf 'dir %s 755 0 0\n' "$ramfs_path" >>"$log"

process_directory "$target_directory"
