#!/bin/bash

# Mount virtual file system
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp

# Execute the customized script
if [ -f /etc/init.d/rc.local ]; then
    sh /etc/init.d/rc.local
fi