#!/bin/sh

# Mount virtual file system
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp

# Configure the network
ifup lo && ifup eth0

# Set environment variables
export SHELL=/bin/sh  # set this explicitly

# Execute the customized script
if [ -f /etc/init.d/rc.local ]; then
    sh /etc/init.d/rc.local
fi

# Launch sh shell
exec sh